/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlacesTEC.capaPresentacion.main;

/**
 *
 * @author sebas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonGesLug = new javax.swing.JButton();
        jButtonSitiosInt = new javax.swing.JButton();
        jButtonRutaViaje = new javax.swing.JButton();
        jButtonRutaCorta = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Places TEC");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButtonGesLug.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonGesLug.setText("Gestionar lugares destino");
        getContentPane().add(jButtonGesLug, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 90));

        jButtonSitiosInt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonSitiosInt.setText("Sitios de interés cercanos");
        jButtonSitiosInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSitiosIntActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSitiosInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 90));

        jButtonRutaViaje.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonRutaViaje.setText("Armar una ruta de viaje");
        getContentPane().add(jButtonRutaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 510, 80));

        jButtonRutaCorta.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonRutaCorta.setText(" Recomendación de viaje más corto");
        getContentPane().add(jButtonRutaCorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, -1, 80));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlacesTEC/capaPresentacion/main/526791.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1065, 824));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSitiosIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSitiosIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSitiosIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGesLug;
    private javax.swing.JButton jButtonRutaCorta;
    private javax.swing.JButton jButtonRutaViaje;
    private javax.swing.JButton jButtonSitiosInt;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
